[package]
name = "dlog"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.28"
crossterm = "0.28"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
anyhow = "1.0"
pulldown-cmark = "0.10"
