[package]
name = "devlog"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.42", features = ["serde"] }
color-eyre = "0.6.5"
crossterm = "0.29.0"
dirs = "6.0.0"
ratatui = { version = "0.29.0", features = ["all-widgets"] }
serde = { version = "1.0.225", features = ["derive"] }

[dev-dependencies]
tempfile = "3.22.0"
