[package]
name = "devlog"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.41", features = ["serde"] }
regex = "1.11.2"
serde = { version = "1.0.219", features = ["derive"] }
